[parity]
mode = "active"
mode_timeout = 300
mode_alarm = 3600
auto_update = "critical"
release_track = "stable"
public_node = false
no_download = false
no_consensus = false
base_path = "/parity-data"
db_path = "/parity-data/chains"
keys_path = "/parity-data/keys"
chain = "foundation"

[ui]
disable = true

[rpc]
disable = false
port = 8545
interface = "0.0.0.0"
cors = []
apis = ["web3", "eth", "net"]
hosts = ["all"]
