apiVersion: v1
kind: Service
metadata:
  name: bitcoin
spec:
  ports:
    - port: 8333
      targetPort: 8333
  selector:
    service: bitcoin
  type: LoadBalancer
  externalTrafficPolicy: Local

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  labels:
    service: bitcoin
  name: bitcoin
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        service: bitcoin
    spec:
      containers:
      - image: thinkmassive/bitcoin
        name: bitcoin
        command:
          - bitcoind
        args:
          - -conf=/etc/bitcoin/bitcoin.conf
          - -datadir=/btcdata
        env:
        - name: BITCOIN_RPC_USER
          valueFrom:
            secretKeyRef:
              name: bitcoin
              key: rpcuser
        - name: BITCOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitcoin
              key: rpcpass
        volumeMounts:
          - mountPath: /btcdata
            name: bitcoin-data
          - mountPath: /etc/bitcoin
            name: bitcoin-config
        resources:
          requests:
            memory: "2Gi"
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      volumes:
        - name: bitcoin-data
          persistentVolumeClaim:
            claimName: bitcoin-pvc
            #fsType: ext4
        - name: bitcoin-config
          configMap:
            name: bitcoin-config
