apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    service: bitcoin
    app: bitcoin
  name: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin
  serviceName: bitcoin
  template:
    metadata:
      name: bitcoin
      labels:
        service: bitcoin
        app: bitcoin
    spec:
      containers:
      - image: thinkmassive/bitcoin
        name: bitcoin
        command:
          - bitcoind
        args:
          - -conf=/etc/bitcoin/bitcoin.conf
          - -datadir=/btcdata
        env:
        - name: BITCOIN_RPC_USER
          valueFrom:
            secretKeyRef:
              name: bitcoin
              key: rpcuser
        - name: BITCOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitcoin
              key: rpcpass
        ports:
          - containerPort: 8332
            protocol: TCP
            name: rpc-port
          - containerPort: 8333
            protocol: TCP
            name: p2p-port
        volumeMounts:
          - mountPath: /btcdata
            name: bitcoin-data
          - mountPath: /etc/bitcoin
            name: bitcoin-config
        resources:
          requests:
            memory: "2Gi"
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      volumes:
        - name: bitcoin-data
          persistentVolumeClaim:
            claimName: bitcoin-pvc
            #fsType: ext4
        - name: bitcoin-config
          configMap:
            name: bitcoin-config
  volumeClaimTemplates:
    - metadata:
        name: bitcoin-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "do-block-storage"
        resources:
          requests:
            storage: 300Gi
